services:
  nest-app:
    build:
      context: .
      dockerfile: ./Dockerfile # Use a Dockerfile for development
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
